{% set name = "uv-dynamic-versioning" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uv_dynamic_versioning-{{ version }}.tar.gz
  sha256: "0dc2aac525d7db15a69b4f1317040d2fd7df71d1f1ae7171cb85080c2b998c23"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dunamai ~=1.23
    - eval-type-backport ~=0.2
    - hatchling ~=1.26
    - jinja2 ~=3.0
    - pydantic ~=2.10
    - tomlkit ~=0.13

test:
  imports:
    - uv_dynamic_versioning
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ninoseki/uv-dynamic-versioning
  summary: Dynamic versioning based on VCS tags for uv/hatch project
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/ninoseki/uv-dynamic-versioning
  dev_url: https://github.com/ninoseki/uv-dynamic-versioning

extra:
  recipe-maintainers:
    - ninoseki
    - tobiasraabe
